---
- hosts: localhost
  tasks:
    - import_tasks: ./auth.yml          # load encryted passwords & keys
    - import_tasks: ./linode.yml        # rebuild linode & update A records for mbrien.net

- hosts: "{{hostname}}"
  remote_user: root
  vars:
      password: 5HyYZiO07N3zE
  tasks:
    - import_tasks: ./hostname.yml      # update hostname
      tags:
       - hosT
    - import_tasks: ./users.yml         # create non-root user
    - import_tasks: ./pacman_conf.yml   # configure pacman
    - import_tasks: ./packages.yml      # install official pkgs
    - import_tasks: ./pip.yml           # install python pkgs
    - import_tasks: ./helper.yml        # install yaourt
    - import_tasks: ./r.yml             # install R pkgs from CRAN

- hosts: "{{hostname}}"
  remote_user: "{{username}}"
  tasks:
    - import_tasks: ./aur.yml           # install pkgs from aur 
    - import_tasks: ./nginx.yml         # configure webserver
      #    - import_tasks: ./tasks/certbot.yml
    - import_tasks: ./tarsnap.yml       # configure tarsnap
    - import_tasks: ./cron.yml          # set up cron jobs
    - import_tasks: ./enable.yml        # enable & start services
      become: true
