- name: create .gitconfig
  file: path=/home/{{user}}/.gitconfig state=touch

- name: add to .gitconfig
  blockinfile:
    dest: /home/{{user}}/.gitconfig
    block: |
       [user]
               name = Martin Brien
               email = martin@martinbrien.com
               username = martinbrien

