---
- hosts: localhost
  become: true
  vars:
      ansible_python_interpreter: /usr/bin/python2
  tasks:
    - import_tasks: ./auth.yml         
    - import_tasks: ./pkgs/localhost_pkgs.yml 
    - pip: name=linode-python executable=/usr/bin/pip2
    - import_tasks: ./kill_node.yml    
    - import_tasks: ./make_node.yml

- hosts: "{{hostname}}"
  remote_user: root
  vars:
      password: 5HyYZiO07N3zE
      # password: $(openssl passwd -1 02ebrienm)
  tasks:
    - import_tasks: ./users.yml           # create non-privilged user 
    - import_tasks: ./pkgs/core_pkgs.yml  # install core AUR packages
    - import_tasks: ./pkgs/cran_pkgs.yml  # install R packages from CRAN
    - import_tasks: ./pkgs/pip3_pkgs.yml  # install python modules

- hosts: "{{hostname}}"
  remote_user: "{{username}}"
  tasks:
    - import_tasks: ./pkgs/trizen.yml     # install trizen from github
    - import_tasks: ./pkgs/aur_pkgs.yml   # set up 
    - import_tasks: ./cron.yml            # set-up cron jobs
    - import_tasks: ./tarsnap.yml         # extact latest tarsnap archive
    - import_tasks: ./dotfiles.yml        # set up config files
    - import_tasks: ./enable.yml          # start daemons
      become: true
