- name: create new vim.rc file
  file: path=/home/{{user}}/.vimrc state=touch group=users owner={{user}} 

- name: add to .vimrc
  blockinfile:
    dest: /home/{{user}}/.vimrc
    block: |
      syntax enable
      colorscheme badwolf

- name: replace block text
  lineinfile: dest=/home/{{user}}/.vimrc regexp="# BEGIN ANSIBLE MANAGED BLOCK" line=""
  tags: vim

- name: replace block text
  lineinfile: dest=/home/{{user}}/.vimrc regexp="# END ANSIBLE MANAGED BLOCK" line=""
  tags: vim
