- name: create .bashrc
  file: path={{ansible_env.HOME}}/.bashrc state=touch

- name: add to .bashrc
  blockinfile:
    dest: {{ ansible_env.HOME }}/.bashrc
    block: |
      export EDITOR='vim'
      alias ls='ls -la --color=auto'


